version: '3'

services:
  # mongoDb:
  #   image: mongo:5.0.7
  #   container_name: Upload_Files
  #   volumes:
  #     - ./:/app
  #   restart: always
  #   platform: linux/x86_64
  #   ports:
  #   - 27017:27017

  backend:
    container_name: backend
    build: .
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app/backend
    # depends_on:
    #   - mongoDb
